######################################################################
# Automatically generated by qmake (2.01a) Di Sep 30 19:05:04 2008
######################################################################

TEMPLATE = app
TARGET = usbrelays
DEPENDPATH += .
INCLUDEPATH += .
LIBS += -lusb -L./lib -lusbrelay

# Input
HEADERS += relaycheckbox.h ../lib/obdev_usb.h ../lib/usbrelay.h lib/usbrelay.h
SOURCES += main.cpp relaycheckbox.cpp
